### ISSUE TITLE
So how to make script?

### ISSUE THREAD

**Issue by YunJongDeuk** [UnityTech/GamesTestAutomationExample#1]
I have object name with x,y position by automation-coordinate Log.
So how to write test script?
Pls show me example script work in testNG.

**Comment by ujappelbe** [comment]
Hi @YunJongDeuk 
I'm not really familiar with testNG, probably you will need to use something like [Appium](http://appium.io/) together with the testNG framework to call clicks on screen of the mobile device. If you're testing a desktop game there's probably some other library you can use for calling the clicks.

I'm going to close this issue as it is outside of the scope of what this project set out to solve, but feel free to add a comment or example when you figure this out. Best of luck 👍
